# Лабораторна робота 1 

## Завдання №5

In [1]:
import random 
import numpy as np

<p>1. Створіть одновимірний масив (вектор) зі зворотнім порядком перших 10 натуральних 
чисел та виведіть його значення. . </p>

In [2]:
vector = np.arange(1, 11)[::-1]
vector

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

<p>2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його послідовністю 
чисел, де кожне наступне число менше попереднього на 3, та виведіть його значення. </p>

In [3]:
start_number = 27
sequence = np.arange(start_number, start_number - 9 * 3, -3)
matrix = sequence.reshape((3, 3))
print("Матриця 3x3:")
print(matrix)

Матриця 3x3:
[[27 24 21]
 [18 15 12]
 [ 9  6  3]]


<p>3. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від 0 до 
1 та виведіть його значення.  </p>

In [17]:
array1 = np.random.random((3, 3))
array1

array([[0.85793581, 0.60034732, 0.3398049 ],
       [0.1029894 , 0.6165453 , 0.81623694],
       [0.07742269, 0.49868171, 0.41114351]])

<p>4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в 
діапазоні від 0 до 1 та обчисліть добуток всіх елементів. </p>

In [19]:
array1 = np.random.random((3, 3))
multiplication = np.prod(array1)
multiplication

7.045221665743858e-06

<p>5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими 
числами в діапазоні від -20 до 20 та виконайте на них поелементні операції додавання, 
віднімання та множення. </p>

In [25]:
array1 = np.random.randint(-20, 20, size=6)
array2 = np.random.randint(-20, 20, size=6)
print(array1, f"\n{array2}")

[ -9  -6  -3   0 -12 -16] 
[-14 -20  -8  13  -7 -13]


In [26]:
array1 + array2 

array([-23, -26, -11,  13, -19, -29])

In [27]:
array1 - array2 

array([  5,  14,   5, -13,  -5,  -3])

In [28]:
array1 * array2 

array([126, 120,  24,   0,  84, 208])

<p>6. Створіть дві матриці 2x2, заповніть їх довільними цілими числами від 6 до 10 та 
знайдіть їх добуток.</p>

In [35]:
array1 = np.random.randint(6, 10, size=9).reshape(3,3)
array2 = np.random.randint(6, 10, size=9).reshape(3,3)
print(array1, f'\n\n{array2}')

[[6 8 8]
 [8 8 6]
 [9 7 7]] 

[[8 6 6]
 [9 8 7]
 [6 6 8]]


In [36]:
array1 * array2

array([[48, 48, 48],
       [72, 64, 42],
       [54, 42, 56]])

<p>7. Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами 
в діапазоні від 1 до 8 та перемножте їх між собою.</p>

In [37]:
array1 = np.random.randint(1, 8, size=6).reshape(3,2)
array2 = np.random.randint(1, 8, size=4).reshape(2,2)
print(array1, f'\n\n{array2}')

[[6 3]
 [1 2]
 [5 5]] 

[[1 1]
 [3 2]]


In [41]:
product = np.matmul(array1, array2)
product

array([[15, 12],
       [ 7,  5],
       [20, 15]])

<p>8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні 
від 1 до 10 та знайдіть її обернену матрицю. </p>

In [43]:
array1 = np.random.randint(1, 10, size=4).reshape(2,2)
array1

array([[4, 5],
       [5, 8]])

In [44]:
np.linalg.inv(array1)

array([[ 1.14285714, -0.71428571],
       [-0.71428571,  0.57142857]])

<p>9. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні 
від 0 до 1 та транспонуйте її. </p>

In [45]:
array1 = np.random.random(9).reshape(3,3)
array1

array([[0.86476026, 0.46807254, 0.58807728],
       [0.35136679, 0.90155515, 0.71596249],
       [0.76610506, 0.0800661 , 0.02158829]])

In [46]:
np.transpose(array1)

array([[0.86476026, 0.35136679, 0.76610506],
       [0.46807254, 0.90155515, 0.0800661 ],
       [0.58807728, 0.71596249, 0.02158829]])

<p>10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю 
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в 
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор. </p>

In [47]:
array1 = np.random.random(12).reshape(3,4)
array1

array([[0.04179454, 0.46728596, 0.90234693, 0.3686469 ],
       [0.51021021, 0.73101019, 0.47108108, 0.59369194],
       [0.33743986, 0.82671053, 0.64581731, 0.75310024]])

In [50]:
vector = np.random.randint(1, 10, size=4).reshape(4,1)
vector

array([[2],
       [9],
       [5],
       [1]])

In [51]:
product = np.matmul(array1, vector)
product

array([[ 9.16954426],
       [10.54860946],
       [12.09746129]])

<p>11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю 
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими 
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.</p>

In [53]:
array1 = np.random.randint(1, 10, size=6).reshape(2,3)
vector = np.random.randint(1, 10, size=3).reshape(3,1)
print(array1, f'\n\n{vector}')

[[4 8 1]
 [2 2 7]] 

[[4]
 [7]
 [6]]


In [54]:
np.matmul(array1, vector)

array([[78],
       [64]])

<p>12. Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в 
діапазоні від 1 до 10 та знайдіть їхню суму. </p>

In [56]:
array1 = np.random.randint(1, 10, size=36).reshape(6,6)
array2 = np.random.randint(1, 10, size=36).reshape(6,6)
print(array1, f'\n\n{array2}')

[[6 7 2 3 8 2]
 [6 7 8 6 4 9]
 [7 8 5 2 2 2]
 [4 4 6 4 7 1]
 [2 7 9 6 6 1]
 [2 5 5 2 6 9]] 

[[7 6 6 4 8 8]
 [5 1 2 5 6 2]
 [6 6 9 1 2 3]
 [1 8 5 6 1 5]
 [3 6 2 1 4 8]
 [6 7 9 9 6 8]]


In [57]:
array1 + array2

array([[13, 13,  8,  7, 16, 10],
       [11,  8, 10, 11, 10, 11],
       [13, 14, 14,  3,  4,  5],
       [ 5, 12, 11, 10,  8,  6],
       [ 5, 13, 11,  7, 10,  9],
       [ 8, 12, 14, 11, 12, 17]])

<p>13. Створіть дві матриці розміром 6x6, заповніть їх випадковими дійсними числами в 
діапазоні від 0 до 1 та знайдіть різницю їх елементів </p>

In [58]:
array1 = np.random.random(size=36).reshape(6,6)
array2 = np.random.random(size=36).reshape(6,6)
print(array1, f'\n\n{array2}')

[[0.77619074 0.68217369 0.43796263 0.23107601 0.68616142 0.20258151]
 [0.01869013 0.58102675 0.49252094 0.08554708 0.96698658 0.47068929]
 [0.72762108 0.7902444  0.55614516 0.73326982 0.34935665 0.2613525 ]
 [0.25677428 0.09110279 0.82350752 0.14820933 0.92569756 0.5173994 ]
 [0.06929282 0.85304216 0.75104931 0.64562868 0.17406472 0.04160404]
 [0.20264278 0.99526517 0.11645086 0.28398057 0.51070838 0.83422669]] 

[[0.54253243 0.80682636 0.43661035 0.15256485 0.78362834 0.25928513]
 [0.28499582 0.34333889 0.86580553 0.66753218 0.06551319 0.57853437]
 [0.95317753 0.10080833 0.61713323 0.71551166 0.92745369 0.52831481]
 [0.50344221 0.47405346 0.16201504 0.37215332 0.97828548 0.48045912]
 [0.49853836 0.97018863 0.6170928  0.78364242 0.39789752 0.16870125]
 [0.62193816 0.20213878 0.86557061 0.51714185 0.49496284 0.77544647]]


In [59]:
array1 - array2 

array([[ 0.23365832, -0.12465267,  0.00135229,  0.07851116, -0.09746692,
        -0.05670362],
       [-0.2663057 ,  0.23768786, -0.37328459, -0.58198509,  0.90147339,
        -0.10784508],
       [-0.22555645,  0.68943607, -0.06098806,  0.01775816, -0.57809703,
        -0.26696231],
       [-0.24666793, -0.38295067,  0.66149248, -0.22394399, -0.05258792,
         0.03694028],
       [-0.42924555, -0.11714647,  0.13395651, -0.13801374, -0.2238328 ,
        -0.12709721],
       [-0.41929538,  0.79312639, -0.74911975, -0.23316128,  0.01574554,
         0.05878023]])

<p>14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в 
діапазоні від -5 до 5 та знайдіть добуток елементів матриці. </p>

In [60]:
array1 = np.random.randint(-5, 5, size=9).reshape(3,3)
array1

array([[ 0, -3, -4],
       [-4, -5,  1],
       [ 1,  3,  4]])

In [61]:
product = np.prod(array1)
product

0

<p>15. Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в 
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у 
кожному рядку матриці. </p>

In [64]:
array1 = np.random.random(size=49).reshape(7, 7)
max_elements = np.max(array1, axis=1)
max_vector = max_elements.reshape(-1, 1)
max_vector

array([[0.73919403],
       [0.64074262],
       [0.81975277],
       [0.84243056],
       [0.85621772],
       [0.85127488],
       [0.92726321]])

<p>Висновок:
<ul>
    <li>було опрацьовано бібліотеку Numpy</li>
    <li>згадано, як працювати з різними масивами</li>
    <li>використано функції пайтон для роботи з даними</li>
</ul></p>